declare type ErrorText = string

/**
 * 校验函数触发的时机
 *
 * Timing of calling validator
 * */
declare enum ValidateTiming {
  OnChange = 0,
  OnBlur = 1,
}

declare type DValueType = string | number | boolean
declare type DFieldType = string | number
/**
 * 表示表单/表单项是否被修改，true - 未被修改过，false - 已被修改过
 *
 * Indicates whether the form or the form item has been modified.
 * true - pristine
 * false - modified
 * */
declare type Pristine = boolean
/**
 * 表示当前表单/表单项是否合法
 *
 * Indicates whether the form or the form item is valid.
 * */
declare type Valid = boolean

interface FormItem<ValueType extends DValueType, FieldType extends DFieldType> {
  field: FieldType
  value: ValueType
  /**
   * 如果 id 没有定义，它的值将会被置为 field 的值
   *
   * If !!id === false, the value of id will be reset to the value of field
   * */
  id?: string | number
  /**
   * Default: ''
   * */
  required?: boolean
  /**
   * Default: true
   * */
  pristine?: Pristine
  /**
   * Default: true
   * */
  valid?: Valid
  /**
   * Default: ''
   * */
  errorText?: string
  /**
   * Default: ValidateTiming.OnChange
   * */
  validateTiming?: ValidateTiming

  /**
   * 这个表单项的校验函数
   *
   * Validate function of the form item
   *
   * Default: (val) => ''
   * */
  validator?(value: ValueType): ErrorText

  /**
   * 格式化函数，每当值发生变化时触发
   *
   * Format the value when the value changes
   * */
  formatter?(value: ValueType): ValueType
}

interface FormOptions<DT extends {}, ST extends any> {
  /**
   * Called in Form.prototype.submit
   * */
  onSubmit?(data: DT): Promise<ST>

  initialValues?: DT
  /**
   * formValidate 方法的 validateAll 参数的默认值
   *
   * The default value of param validateAll of method formValidate
   *
   * Default: true
   * */
  validateAll?: boolean
}

declare type TupleToUnion<T, K extends string> = T extends Array<
  {
    [k in K]: infer E
  }
>
  ? E
  : never
declare type GetFieldType<
  FormItems extends FormItem<any, any>[]
> = TupleToUnion<FormItems, 'field'>
declare type GetValueType<
  FormItems extends FormItem<any, any>[]
> = TupleToUnion<FormItems, 'value'>
declare type NonUnknown<T> = T extends unknown ? never : T
declare type GetIdType<FormItems extends FormItem<any, any>[]> =
  | NonUnknown<TupleToUnion<FormItems, 'id'>>
  | GetFieldType<FormItems>
declare type FormItemsData<
  FormItems extends FormItem<DValueType, DFieldType>[]
> = {
  [k in GetFieldType<FormItems>]: GetValueType<FormItems>
}

declare class Form<
  FormItems extends FormItem<any, any>[],
  FormDataType extends FormItemsData<FormItems>,
  ReturnTypeOfSubmit extends any
> {
  private readonly options

  /**
   * @desc 表单项数组
   *
   * @desc Array of form items
   * */
  readonly items: Array<
    FormItem<
      GetValueType<FormItems>,
      GetFieldType<FormItems> & {
        id: string | number
      }
    >
  >

  /**
   * @desc 当前表单数据，由表单项数组生成
   *
   * @desc Data of the form, generated by form items
   * */
  readonly data: FormDataType

  pristine: Pristine

  valid: Valid

  /**
   * @desc 当前表单应该显示的错误信息
   *
   * @desc The current errorText of the form
   * */
  errorText: string

  constructor(
    formItems: FormItems,
    options?: FormOptions<FormDataType, ReturnTypeOfSubmit | FormDataType>,
  )

  getItem: (
    field: TupleToUnion,
  ) =>
    | FormItem<
        TupleToUnion,
        TupleToUnion & {
          id: DFieldType
        }
      >
    | undefined

  /**
   * @desc 更新与参数 field 对应的表单项的值
   *
   * @desc Update the value of the form item that matched the param `field`
   * */
  itemChange: (field: TupleToUnion, value: TupleToUnion) => void

  /**
   * @desc 校验与参数 field 对应的表单项
   *
   * @desc Validate the value of the form item that matched the param `field`
   * */
  itemValidate: (field: TupleToUnion) => string

  /**
   * @desc 校验整个表单，更新表单实例属性：valid, pristine, errorText, data, items
   * @param validateAll   是否校验所有表单项
   *                      true - 校验所有表单项
   *                      false - 当遇到第一个校验错误的表单项时，停止对其他表单项的校验
   *
   *                      默认值: this.options.validateAll
   *
   * @desc Form validate, update the value of properties: valid, pristine, errorText, data, items
   * @param validateAll   Whether validate all the form item in the form
   *                      true - validate all
   *                      false - stop validate other form items when the first form item with a validation error is encountered
   *
   *                      Default: this.options.validateAll
   *
   * @return ErrorText
   * */
  formValidate: (validateAll?: boolean) => string

  /**
   * @desc 在提交之前会先做一次表单校验（运行 formValidate）
   *
   * @desc Method formValidate will be called before run the onSubmit function in this method
   * */
  submit: () => Promise<FormDataType | ReturnTypeOfSubmit>

  /**
   * @desc 重置表单
   *
   * @desc Reset form
   *
   * @param values             Default: this.options.initialValues
   * */
  reset: (values?: FormDataType) => void

  /**
   * @desc 用参数 value 的值重置与参数 field 对应的表单项
   *
   * @desc Reset form item that matched the param field with the param value
   *
   * @param field
   * @param value              Default: this.options.initialValues[field]
   * */
  resetItem: (field: TupleToUnion, value?: TupleToUnion) => void

  /**
   * @desc 清除表单/表单项的校验结果
   *
   * @desc Clear the validate result of the form or the form item that matched the param field
   *
   * @param [field]            If `!!field === true`, it will clear the validate result of the form item that matched the param field
   *                           else, if will clear the validate result of the form
   * */
  clearValidateResult: (field?: TupleToUnion | undefined) => void
}

declare class FormItemsManager<
  FormItems extends {
    [id: string]: FormItem<any, any>
  }
> {
  private readonly allItems

  constructor(formItems: FormItems)

  getItem: <Id extends keyof FormItems>(
    id: Id,
  ) =>
    | (FormItems[Id] & {
        id: Id
      })
    | undefined

  getItems: <Ids extends (keyof FormItems)[]>(
    ids: Ids,
  ) => (
    | (FormItems[keyof FormItems] & {
        id: keyof FormItems
      })
    | undefined)[]
}

export {
  DFieldType,
  DValueType,
  ErrorText,
  Form,
  FormItem,
  FormItemsData,
  FormItemsManager,
  FormOptions,
  GetFieldType,
  GetIdType,
  GetValueType,
  NonUnknown,
  Pristine,
  TupleToUnion,
  Valid,
  ValidateTiming,
}
